### ISSUE TITLE
Fails to download MC bedrock server

### ISSUE THREAD

**Issue by KroBaar** [crowbarmaster/BedrockService#2]
When attempting to start bedrockservice.exe for the first time with or without Minecraft Bedrock server already downloaded. 

The output is as follows:

Checking MCS Version and fetching update if needed...
Updater resulted in error: An error occurred while sending the request.
Updates Enabled, will be checked in: 9909.057 seconds.
Starting service...
ERROR: Got zipfile exception! Could not find file 'D:\Games\Minecraft\BedrockService\MCSFiles\Update.zip'..
!!Deleting entire directory!! Press Enter to continue...

Checking your Updater.cs file, it appears to be failing at line 22: content = await client.GetStringAsync("https://www.minecraft.net/en-us/download/server/bedrock");

I've added bedrockservice.exe to both inbound and outbound firewall rules for good measure. There must be some other security setting I'm overlooking that is blocking this from working.

I am running Windows 10 21H1 build 19043.1165 with .NET v4.8.04084

**Comment by KroBaar** [comment]
Ok, I downloaded the code so I could do some debugging to try and figure out what is going wrong. It appears that the Minecraft website is rejecting your httpClient connection. It seems that some webservers employ some bot detection and reject clients they don't like. I referenced this article:

https://stackoverflow.com/questions/48790438/why-can-the-c-sharp-httpclient-not-call-this-url-always-times-out

I commented out your UserAgent request header and added the following:

            client.DefaultRequestHeaders.Add("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/apng,*/*;q=0.8");
            client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("gzip"));
            client.DefaultRequestHeaders.AcceptEncoding.Add(new StringWithQualityHeaderValue("deflate"));
            client.DefaultRequestHeaders.Add("Accept-Language", "en-GB,en;q=0.9,en-US;q=0.8");
            client.DefaultRequestHeaders.Add("Connection", "keep-alive");
            client.DefaultRequestHeaders.Add("Cache-Control", "no-cache");
            client.DefaultRequestHeaders.Add("Pragma", "no-cache");
            client.DefaultRequestHeaders.Add("User-Agent", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko; Google Page Speed Insights) Chrome/27.0.1453 Safari/537.36");

That worked enough for the code to continue past line 22 in Updater.cs :
client.GetStringAsync("https://www.minecraft.net/en-us/download/server/bedrock");

However, now the pattern regex match isn't finding anything and the string DownloadPath is empty - perhaps due to the headers I used. I don't know enough about how you were parsing the page in order to fix this further.

**Comment by crowbarmaster** [comment]
Hello! Thanks for you interest! I have solved that issue, as well as quite a few other issues! Source is updated, but a few bugs still exist. This project was set aside for a while, but steady work will continue soon! If you want to fix your current copy, have a look at updater.cs as it stands now. You should be able to swap the whole file out. Let me know if you have any other issues!
